### ISSUE TITLE
Error occured while starting miqsel on fedora 29

### ISSUE THREAD

**Issue by ganeshhubale** [digitronik/miqsel#8] opened 2019-02-01 14:57 UTC
- Followed steps from README file.
- Default python version is ```python 2.7.15```
- OS: ```Fedora 29```
- I can able install  ```miqsel``` but once I executed ```start or stop``` command following error occurs.
- Let me know if this is mainly related to ```Integration test``` repo. setup or just permission denied.
@digitronik Please let know if you have faced this error before:

```
Traceback (most recent call last):
  File "/home/ghubale/.local/bin/miqsel", line 11, in <module>
    load_entry_point('miqsel==1.2', 'console_scripts', 'miqsel')()
  File "/home/ghubale/.local/lib/python2.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/ghubale/.local/lib/python2.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/ghubale/.local/lib/python2.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ghubale/.local/lib/python2.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ghubale/.local/lib/python2.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/ghubale/.local/lib/python2.7/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/home/ghubale/.local/lib/python2.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/ghubale/.local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/ghubale/.local/lib/python2.7/site-packages/miqsel/miqsel.py", line 167, in start
    container = get_container()
  File "/home/ghubale/.local/lib/python2.7/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/home/ghubale/.local/lib/python2.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/ghubale/.local/lib/python2.7/site-packages/miqsel/miqsel.py", line 130, in get_container
    return connection.client.containers.get(connection.conf.get("container_name"))
  File "/home/ghubale/.local/lib/python2.7/site-packages/docker/models/containers.py", line 862, in get
    resp = self.client.api.inspect_container(container_id)
  File "/home/ghubale/.local/lib/python2.7/site-packages/docker/utils/decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/home/ghubale/.local/lib/python2.7/site-packages/docker/api/container.py", line 755, in inspect_container
    self._get(self._url("/containers/{0}/json", container)), True
  File "/home/ghubale/.local/lib/python2.7/site-packages/docker/utils/decorators.py", line 46, in inner
    return f(self, *args, **kwargs)
  File "/home/ghubale/.local/lib/python2.7/site-packages/docker/api/client.py", line 225, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
  File "/home/ghubale/.local/lib/python2.7/site-packages/requests/sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "/home/ghubale/.local/lib/python2.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/ghubale/.local/lib/python2.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/ghubale/.local/lib/python2.7/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', error(13, 'Permission denied'))
```

**Comment by digitronik** [comment] 2019-02-01 15:30
@ganeshhubale you need  root privilege.  Please check your docker able to run without root or not.

**Comment by digitronik** [comment] 2019-02-01 15:31
@ganeshhubale fallow `readme`... If problem not solved let me know. I tested with `fedora-29`. its working awesome.

**Comment by ganeshhubale** [comment] 2019-02-01 17:31
@digitronik Thank you for reply. 
Now I am not getting this error but still ```miqsel``` is not running with ```start``` command and also it is not showing any error.
I will let you know once if I get any error.

**Comment by digitronik** [comment] 2019-02-02 08:00
1. after adding `non root` user in `docker` group best practice is to restart `system`.
2. When we start miqsel on new system then it will take time as its `downloading` docker images.

Its not a bug.. closing this issue. Please, let me know if it not works. Thanks for raising issue.

**Closed as completed by digitronik** 2019-02-02 08:00 UTC

**Comment by ganeshhubale** [comment] 2019-02-02 09:40
Now it is working for me.
Thanks
